# Project Icarus - Main Image Recipe
# Based on Bazzite KDE 

name: project-icarus
description: Optimized Fedora-based gaming and workstation image
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - gum
      - yad
      - zenity
      - retroarch
      - plymouth-theme-spinner

  - type: files
    files:
      - usr: files/system/usr
      - etc/systemd/system: files/systemd/icarus-user-rename.service
      - usr/share/icarus/plymouth: modules/plymouth/win98
      - usr/share/icarus/ascii.txt: ascii.txt
      - etc/skel: modules/reactionary # Kopiert Win98-Defaults für neue User

  - type: script
    scripts:
      - setup-plymouth.sh
      - setup-ui-theme.sh
      - finalize-system.sh
